version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    ports:
      - "3000:3000"
#    networks:
#      - monitoring
    volumes:
      - /data/grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
     INFLUXDB_DB: graylog
     INFLUXDB_ADMIN_ENABLED: "true"
     INFLUXDB_ADMIN_USER: admin 
     INFLUXDB_ADMIN_PASSWORD: randompassword12345
    volumes:
      - /data/influxdb-volume:/var/lib/influxdb
